name: page generation CI/CD work-flow

env:
  MONGO_DATABASE_URI: ${{ secrets.MONGO_DATABASE_URI_E_COM }}
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME_E_COM }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD_E_COM }}
  KEY_JWT: ${{ secrets.KEY_JWT_E_COM }}
  DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD_E_COM}}
  PORT: ${{ secrets.PORT_E_COM}}
on:
  pull_request:
    branches: [ develop ]

jobs:
  test-develop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test

  build-develop:
    if: ${{ always() }}
    needs: [ test-develop ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
